#test db
#spring.h2.console.enabled=true

spring:
  profiles:
    active: dev

# dev 환경
---
spring:
  profiles: prod
    include: real-db
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  resources:
    static-locations: classpath:/resources,classpath:/static/,classpath:/templates/static/,file:../Right-Hand-Imgs/

  redis:
    port: 6379
    host: 127.0.0.1
  session:
    store-type: redis
  thymeleaf:
    check-template: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 120MB

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

---

spring:
  profiles: dev
    include: dev-db
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  resources:
    static-locations: classpath:/resources,classpath:/static/,classpath:/templates/static/,file:../Right-Hand-Imgs/

# test 환경
---
spring:
  profiles: test
  h2:
    console:
      enabled: true
