#test db
#spring.h2.console.enabled=true

spring:
  profiles:
    active: dev
  thymeleaf:
    check-template: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 120MB

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# dev 환경
---
spring:
  profiles: dev
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://121.134.77.202:3408/RIGHT_HAND_DEV
    username: todos
    password: wkdqkr3266@
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  resources:
    static-locations: classpath:/resources,classpath:/static/,classpath:/templates/static/,file:../Right-Hand-Imgs/

---

spring:
  profiles: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://121.134.77.202:3408/RIGHT_HAND_DEV
    username: todos
    password: wkdqkr3266@
    jpa:
      show-sql: true
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    resources:
      static-locations: classpath:/resources,classpath:/static/,classpath:/templates/static/,file:../Right-Hand-Imgs/

# test 환경
---
spring:
  profiles: test
  h2:
    console:
      enabled: true



# prod(deploy) 환경
---
spring:
  profiles: prod
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
#  resources:
#  static-locations:

